version: '2'
services:
  dev:
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - TEST_STORAGE_API_URL
      - TEST_STORAGE_API_TOKEN
      - TEST_COMPONENT_ID
      - TEST_AWS_ACCESS_KEY_ID
      - TEST_AWS_SECRET_ACCESS_KEY
      - TEST_AWS_REGION
      - TEST_AWS_S3_BUCKET
      - TEST_AZURE_ACCOUNT_NAME
      - TEST_AZURE_ACCOUNT_KEY
      - TEST_AZURE_CONTAINER_NAME
      - TEST_GCP_SERVICE_ACCOUNT
      - TEST_GCP_BUCKET
